version: "3.8"

services:

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - ./var/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
